package main.br.edu.clinica.model;

public enum Setor {
    RECEPCIONISTA, MEDICO, ENFERMEIRO, PACIENTE,
    CONSULTA, EXAME, RESULTADO_EXAME, RECEITA, ATESTADO, ENCAMINHAMENTO,
    FORMA_PAGAMENTO, PLANO_SAUDE, PAGAMENTO;
}
